version: 0.2
phases:
  install:
    commands:
        - npm install
  pre_build:
    commands:
        - npm test
        - docker login -u AWS -p $(aws ecr get-login-password --region eu-central-1) $REGISTRY_URL
  build:
    commands:
        - echo Build started...
        - docker build -t $IMAGE_NAME:$BUILD_ID --build-arg NODE_ENV=prod .
        - docker tag $IMAGE_NAME:$BUILD_ID $REGISTRY_URL/$IMAGE_NAME:$BUILD_ID
  post_build:
    commands:
        - echo Build completed
        - docker push $REGISTRY_URL/$IMAGE_NAME
        - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_NAME $REGISTRY_URL/$IMAGE_NAME:$BUILD_ID > imagedefinitions.json
artifacts:
    files: imagedefinitions.json